version: "3.8"
services:
  rabbitmq:
    networks:
      - tomas-the-tank
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
# Don't know if this is required, but it made docker compose up fail :(
#    build:
#      context: docker/
    ports:
      - "1883:1883" # MQTT port
      - "5672:5672"
      - "15672:15672" # WebUI port
      - "1885:15675" # WS Mqtt port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    volumes:
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      # - ./config/conf.d/*:/etc/rabbitmq/conf.d/:ro

networks:
  tomas-the-tank:
    external: true
