version: "3"

services:
  external:
    container_name: external
    image: external-website
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
      - TZ=Pacific/Auckland
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"