/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderDTO
 */
export interface CreateOrderDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrderDTO
     */
    steps?: Array<string>;
}

/**
 * Check if a given object implements the CreateOrderDTO interface.
 */
export function instanceOfCreateOrderDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateOrderDTOFromJSON(json: any): CreateOrderDTO {
    return CreateOrderDTOFromJSONTyped(json, false);
}

export function CreateOrderDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'steps': !exists(json, 'steps') ? undefined : json['steps'],
    };
}

export function CreateOrderDTOToJSON(value?: CreateOrderDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'steps': value.steps,
    };
}

