/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderStep
 */
export interface OrderStep {
    /**
     * 
     * @type {string}
     * @memberof OrderStep
     */
    orderStatus?: OrderStepOrderStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OrderStep
     */
    stepId?: string;
}


/**
 * @export
 */
export const OrderStepOrderStatusEnum = {
    NotStarted: 'NOT_STARTED',
    Started: 'STARTED',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;
export type OrderStepOrderStatusEnum = typeof OrderStepOrderStatusEnum[keyof typeof OrderStepOrderStatusEnum];


/**
 * Check if a given object implements the OrderStep interface.
 */
export function instanceOfOrderStep(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderStepFromJSON(json: any): OrderStep {
    return OrderStepFromJSONTyped(json, false);
}

export function OrderStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStep {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderStatus': !exists(json, 'orderStatus') ? undefined : json['orderStatus'],
        'stepId': !exists(json, 'stepId') ? undefined : json['stepId'],
    };
}

export function OrderStepToJSON(value?: OrderStep | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderStatus': value.orderStatus,
        'stepId': value.stepId,
    };
}

