version: '3.7'
services:

  spring_template:
    build:
      context: ./
    container_name: spring_template_mongodb
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container
    environment:
      - SPRING_MONGODB_DATABASE=proddb
      - SPRING_MONGODB_HOST=mongodb_container

  mongodb_container:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    build:
      context: docker/
    ports:
      - "1883:1883" # MQTT port
      - "5672:5672"
      - "15672:15672" # WebUI port
      - "1885:15675" # WS Mqtt port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    volumes:
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      # - ./config/conf.d/*:/etc/rabbitmq/conf.d/:ro

volumes:
  mongodb_data_container:


