version: '3.7'
services:

  backend:
    image: supervisor_backend:prod
    container_name: supervisor_backend 
    networks:
      - system
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_MONGODB_DATABASE=proddb
      - SPRING_MONGODB_HOST=mongodb_container
      - SPRING_MONGODB_USERNAME=root
      - SPRING_MONGODB_PASSWORD=example
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123

networks:
  system:
    external: true
