version: "3.2"

services:
    influxdb:
      image: influxdb:2.7-alpine
      container_name: influxdb
      restart: always
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=admin
        - DOCKER_INFLUXDB_INIT_PASSWORD=password
        - DOCKER_INFLUXDB_INIT_ORG=group-6
        - DOCKER_INFLUXDB_INIT_BUCKET=sensor-data
        - DOCKER_INFLUXDB_INIT_RETENTION=4w
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=random-token-value-123-456-789
      ports:
        - '8086:8086'
      volumes:
        - ./data/:/var/lib/influxdb
