version: '3.7'
services:

  assembly_backend:
    networks:
      - tomas-the-tank
    build:
      context: ./
    container_name: assembly_system
    restart: always
    ports:
      - "8080:8080"

networks:
  tomas-the-tank:
    external: true


